### ISSUE TITLE
Make irods_session robust for long montoring periods

### ISSUE THREAD

**Issue by paulborgermans** [kuleuven/mango-ingest#8]
- [x] Refresh the irods_session pro-actively
- [ ] Check if the irods_session is still alive before using it to upload

**Comment by ghuls** [comment]
Also when uploading big files (multiple hundred of GB/TB) (and calculating the checkum) the session currently can expire:

```
...
CRITICAL:irods.connection:The read operation timed out
ERROR:irods.connection:Could not receive server response
...
```
